<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TracerStudyQuestion;

class TracerStudyQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // ── Status Pekerjaan ──────────────────────────────────────────────
            [
                'section'    => 'status_pekerjaan',
                'field_name' => 'status_pekerjaan',
                'label'      => 'Status Pekerjaan Saat Ini',
                'type'       => 'radio',
                'options'    => [
                    'bekerja'                    => 'Bekerja',
                    'wirausaha'                  => 'Wirausaha / Wiraswasta',
                    'melanjutkan_studi'          => 'Melanjutkan Studi',
                    'ppg'                        => 'Mengikuti PPG (Profesi Guru)',
                    'belum_bekerja'              => 'Belum / Tidak Bekerja',
                    'belum_memungkinkan_bekerja' => 'Belum Memungkinkan Bekerja',
                ],
                'is_required' => true,
                'is_active'   => true,
                'sort_order'  => 1,
                'helper_text' => 'Pilih status yang paling sesuai dengan kondisi Anda saat ini.',
            ],

            // ── Data Pekerjaan ────────────────────────────────────────────────
            [
                'section'    => 'data_pekerjaan',
                'field_name' => 'waktu_tunggu_kerja',
                'label'      => 'Berapa bulan setelah lulus Anda mendapatkan pekerjaan ini?',
                'type'       => 'number',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 1,
                'helper_text' => 'Isi 0 jika sudah bekerja sebelum lulus.',
            ],
            [
                'section'    => 'data_pekerjaan',
                'field_name' => 'nama_perusahaan',
                'label'      => 'Nama Perusahaan / Instansi Tempat Bekerja',
                'type'       => 'text',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 2,
                'helper_text' => null,
            ],
            [
                'section'    => 'data_pekerjaan',
                'field_name' => 'jenis_perusahaan',
                'label'      => 'Jenis / Sektor Perusahaan',
                'type'       => 'select',
                'options'    => [
                    'instansi_pemerintah' => 'Instansi Pemerintah',
                    'bumn'                => 'BUMN / BUMD',
                    'swasta_nasional'     => 'Swasta Nasional',
                    'perusahaan_asing'    => 'Perusahaan Asing / Multinasional',
                    'wirausaha'           => 'Wirausaha / Mandiri',
                    'ngo'                 => 'LSM / NGO',
                    'lainnya'             => 'Lainnya',
                ],
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 3,
                'helper_text' => null,
            ],
            [
                'section'    => 'data_pekerjaan',
                'field_name' => 'tingkat_tempat_kerja',
                'label'      => 'Tingkat / Skala Tempat Kerja',
                'type'       => 'select',
                'options'    => [
                    'lokal'        => 'Lokal / Wilayah',
                    'nasional'     => 'Nasional',
                    'multinasional'=> 'Multinasional / Internasional',
                ],
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 4,
                'helper_text' => null,
            ],
            [
                'section'    => 'data_pekerjaan',
                'field_name' => 'relevansi_pekerjaan',
                'label'      => 'Seberapa erat hubungan pekerjaan Anda dengan bidang studi?',
                'type'       => 'radio',
                'options'    => [
                    'sangat_relevan' => 'Sangat Erat',
                    'relevan'        => 'Erat',
                    'cukup_relevan'  => 'Cukup Erat',
                    'kurang_erat'    => 'Kurang Erat',
                    'tidak_relevan'  => 'Tidak Sama Sekali',
                ],
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 5,
                'helper_text' => null,
            ],
            [
                'section'    => 'data_pekerjaan',
                'field_name' => 'penghasilan',
                'label'      => 'Penghasilan Per Bulan (Rp)',
                'type'       => 'number',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 6,
                'helper_text' => 'Isi dalam satuan Rupiah, contoh: 5000000',
            ],

            // ── Pencarian Kerja ───────────────────────────────────────────────
            [
                'section'    => 'pencarian_kerja',
                'field_name' => 'kapan_mencari_kerja',
                'label'      => 'Kapan Anda mulai mencari pekerjaan?',
                'type'       => 'radio',
                'options'    => [
                    'sebelum_lulus' => 'Sebelum Lulus',
                    'setelah_lulus' => 'Setelah Lulus',
                ],
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 1,
                'helper_text' => null,
            ],
            [
                'section'    => 'pencarian_kerja',
                'field_name' => 'cara_cari_kerja',
                'label'      => 'Bagaimana cara Anda mencari pekerjaan? (pilih semua yang sesuai)',
                'type'       => 'checkbox',
                'options'    => [
                    'iklan_online'       => 'Iklan Online / Job Portal',
                    'relasi'             => 'Melalui Relasi / Kenalan',
                    'rekrutmen_kampus'   => 'Rekrutmen di Kampus / Career Fair',
                    'melamar_langsung'   => 'Melamar Langsung ke Perusahaan',
                    'media_sosial'       => 'Media Sosial (LinkedIn, dll.)',
                    'magang'             => 'Berlanjut dari Magang/PKL',
                    'lainnya'            => 'Lainnya',
                ],
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 2,
                'helper_text' => null,
            ],
            [
                'section'    => 'pencarian_kerja',
                'field_name' => 'jumlah_lamaran',
                'label'      => 'Berapa banyak lamaran yang Anda kirim?',
                'type'       => 'number',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 3,
                'helper_text' => null,
            ],

            // ── Data Wirausaha ────────────────────────────────────────────────
            [
                'section'    => 'data_wirausaha',
                'field_name' => 'nama_usaha',
                'label'      => 'Nama Usaha / Bisnis',
                'type'       => 'text',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 1,
                'helper_text' => null,
            ],
            [
                'section'    => 'data_wirausaha',
                'field_name' => 'bidang_usaha',
                'label'      => 'Bidang Usaha',
                'type'       => 'text',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 2,
                'helper_text' => 'Contoh: Kuliner, Teknologi, Fashion, dll.',
            ],
            [
                'section'    => 'data_wirausaha',
                'field_name' => 'jumlah_karyawan',
                'label'      => 'Jumlah Karyawan',
                'type'       => 'number',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 3,
                'helper_text' => null,
            ],
            [
                'section'    => 'data_wirausaha',
                'field_name' => 'omzet_usaha',
                'label'      => 'Omzet Usaha Per Bulan (Rp)',
                'type'       => 'number',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 4,
                'helper_text' => null,
            ],

            // ── Data Studi Lanjut ─────────────────────────────────────────────
            [
                'section'    => 'data_studi',
                'field_name' => 'nama_institusi',
                'label'      => 'Nama Perguruan Tinggi / Lembaga',
                'type'       => 'text',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 1,
                'helper_text' => null,
            ],
            [
                'section'    => 'data_studi',
                'field_name' => 'jurusan_studi',
                'label'      => 'Program Studi / Jurusan',
                'type'       => 'text',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 2,
                'helper_text' => null,
            ],
            [
                'section'    => 'data_studi',
                'field_name' => 'sumber_biaya',
                'label'      => 'Sumber Biaya Studi',
                'type'       => 'select',
                'options'    => [
                    'beasiswa_pemerintah' => 'Beasiswa Pemerintah (LPDP, Bidikmisi, dll.)',
                    'beasiswa_swasta'     => 'Beasiswa Swasta / Perusahaan',
                    'biaya_sendiri'       => 'Biaya Sendiri',
                    'tanggungan_ortu'     => 'Tanggungan Orang Tua',
                    'lainnya'             => 'Lainnya',
                ],
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 3,
                'helper_text' => null,
            ],

            // ── Kompetensi ────────────────────────────────────────────────────
            [
                'section'    => 'kompetensi',
                'field_name' => 'kompetensi_saat_lulus',
                'label'      => 'Kompetensi apa yang Anda kuasai saat lulus? (pilih semua yang sesuai)',
                'type'       => 'checkbox',
                'options'    => [
                    'kemampuan_komunikasi'      => 'Kemampuan Komunikasi',
                    'kerjasama_tim'             => 'Kerjasama Tim',
                    'pemecahan_masalah'         => 'Pemecahan Masalah',
                    'kemampuan_analisis'        => 'Kemampuan Analisis',
                    'kepemimpinan'              => 'Kepemimpinan',
                    'kemampuan_teknologi'       => 'Kemampuan Teknologi/IT',
                    'pengetahuan_bidang_studi'  => 'Pengetahuan Bidang Studi',
                    'kreativitas_inovasi'       => 'Kreativitas & Inovasi',
                    'kemampuan_bahasa_asing'    => 'Kemampuan Bahasa Asing',
                    'etika_profesional'         => 'Etika Profesional',
                ],
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 1,
                'helper_text' => null,
            ],
            [
                'section'    => 'kompetensi',
                'field_name' => 'kompetensi_diperlukan',
                'label'      => 'Kompetensi apa yang paling dibutuhkan di dunia kerja? (pilih semua yang sesuai)',
                'type'       => 'checkbox',
                'options'    => [
                    'kemampuan_komunikasi'      => 'Kemampuan Komunikasi',
                    'kerjasama_tim'             => 'Kerjasama Tim',
                    'pemecahan_masalah'         => 'Pemecahan Masalah',
                    'kemampuan_analisis'        => 'Kemampuan Analisis',
                    'kepemimpinan'              => 'Kepemimpinan',
                    'kemampuan_teknologi'       => 'Kemampuan Teknologi/IT',
                    'pengetahuan_bidang_studi'  => 'Pengetahuan Bidang Studi',
                    'kreativitas_inovasi'       => 'Kreativitas & Inovasi',
                    'kemampuan_bahasa_asing'    => 'Kemampuan Bahasa Asing',
                    'etika_profesional'         => 'Etika Profesional',
                ],
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 2,
                'helper_text' => null,
            ],

            // ── Kepuasan & Saran ──────────────────────────────────────────────
            [
                'section'    => 'kepuasan_feedback',
                'field_name' => 'kepuasan_pendidikan',
                'label'      => 'Seberapa puas Anda dengan kualitas pendidikan yang diterima? (1-5)',
                'type'       => 'radio',
                'options'    => [
                    '1' => '1 — Sangat Tidak Puas',
                    '2' => '2 — Tidak Puas',
                    '3' => '3 — Cukup',
                    '4' => '4 — Puas',
                    '5' => '5 — Sangat Puas',
                ],
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 1,
                'helper_text' => null,
            ],
            [
                'section'    => 'kepuasan_feedback',
                'field_name' => 'saran_kurikulum',
                'label'      => 'Saran untuk Kurikulum',
                'type'       => 'textarea',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 2,
                'helper_text' => 'Tuliskan saran Anda untuk perbaikan kurikulum.',
            ],
            [
                'section'    => 'kepuasan_feedback',
                'field_name' => 'saran_fasilitas',
                'label'      => 'Saran untuk Fasilitas',
                'type'       => 'textarea',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 3,
                'helper_text' => 'Tuliskan saran Anda untuk perbaikan fasilitas.',
            ],
            [
                'section'    => 'kepuasan_feedback',
                'field_name' => 'saran_umum',
                'label'      => 'Saran Umum',
                'type'       => 'textarea',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 4,
                'helper_text' => 'Tuliskan saran umum Anda untuk institusi.',
            ],

            // ── Kontak ────────────────────────────────────────────────────────
            [
                'section'    => 'kontak',
                'field_name' => 'email_saat_ini',
                'label'      => 'Alamat Email Aktif',
                'type'       => 'email',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 1,
                'helper_text' => null,
            ],
            [
                'section'    => 'kontak',
                'field_name' => 'no_telp_saat_ini',
                'label'      => 'Nomor Telepon / WhatsApp Aktif',
                'type'       => 'text',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 2,
                'helper_text' => null,
            ],
            [
                'section'    => 'kontak',
                'field_name' => 'linkedin',
                'label'      => 'Profil LinkedIn (opsional)',
                'type'       => 'url',
                'options'    => null,
                'is_required' => false,
                'is_active'   => true,
                'sort_order'  => 3,
                'helper_text' => 'Contoh: https://linkedin.com/in/namaanda',
            ],
        ];

        foreach ($questions as $q) {
            TracerStudyQuestion::updateOrCreate(
                ['field_name' => $q['field_name'], 'section' => $q['section']],
                $q
            );
        }

        $this->command->info('TracerStudyQuestion seeded: ' . count($questions) . ' pertanyaan.');
    }
}
